version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local-compose
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."

  # The Spring Boot Backend Service
  backend:
    build: . # Tells Docker to build from the Dockerfile in the current directory
    ports:
      - "8080:8080"
    environment:
      # Pass the Gemini API key as an environment variable
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Tell Spring Boot how to find DynamoDB inside the Docker network
      - AMAZON_DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb # Ensures DynamoDB starts before the backend

  # The React Frontend Service
  frontend:
    build:
      context: ./chatbot-ui # Tells Docker to build from the Dockerfile in the chatbot-ui directory
    ports:
      - "3000:80" # Map host port 3000 to the container's Nginx port 80
    depends_on:
      - backend # Ensures the backend is running before the frontend starts